language: csharp
mono: latest
dotnet: 3.1.302
before_install:
 - sudo apt-get update
install:
 - dotnet restore
script:
 - dotnet build ./MintPlayer.SeasonCheck/MintPlayer.SeasonCheck.csproj --configuration Release --no-restore
 - dotnet test --no-restore --verbosity normal
sudo: required
